service: wekin-api-prod
# service: wekin-api-dev
api_version: 1.0.0
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 2
env_variables:
  SQL_USER: postgres
  # SQL_USER: wekin
  SQL_PASSWORD: dnlzlsjwmfru!
  SQL_DATABASE: wekin
  INSTANCE_CONNECTION_NAME: wekinproject:asia-northeast1:wekin-production
  # INSTANCE_CONNECTION_NAME: wekinproject:asia-northeast1:wekin-dev
  SQL_CLIENT: pg
beta_settings:
  cloud_sql_instances: wekinproject:asia-northeast1:wekin-production
  # cloud_sql_instances: wekinproject:asia-northeast1:wekin-dev
